name: Update Trailframe Version

on:
  repository_dispatch:
    types:
      - trailframe-release

jobs:
  Update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v7

      - name: Update version
        run: |
          VERSION=${{ github.event.client_payload.version }}

          jq '.version = "${{ github.event.client_payload.version }}"' trailframe/config.json > trailframe/config.json.tmp
          mv trailframe/config.json.tmp trailframe/config.json
          echo -e "## ${{ github.event.client_payload.version }}\n- Updated Trailframe to version [\`${{ github.event.client_payload.version }}\`](https://github.com/Sildra/trailframe/releases/tag/${{ github.event.client_payload.version }})\n" | cat - trailframe/CHANGELOG.md > trailframe/CHANGELOG.md.tmp
          mv trailframe/CHANGELOG.md.tmp trailframe/CHANGELOG.md

      - name: Commit
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

          git add -u
          git commit -m "Release ${VERSION}" || true
          git push